/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      // ─── LIGHT MODE COLORS (from desktop zip) ───────────────────────────
      colors: {
        // Light mode
        "primary": "#006877",
        "on-primary": "#ffffff",
        "primary-container": "#00e0ff",
        "on-primary-container": "#005f6d",
        "primary-fixed": "#a5eeff",
        "primary-fixed-dim": "#00daf8",
        "secondary": "#a90097",
        "on-secondary": "#ffffff",
        "secondary-container": "#d300bd",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#ffd7f0",
        "secondary-fixed-dim": "#fface8",
        "tertiary": "#0c6e00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#24ec00",
        "on-tertiary-container": "#0a6500",
        "tertiary-fixed": "#78ff5d",
        "tertiary-fixed-dim": "#23e600",
        "background": "#f8f9fa",
        "on-background": "#191c1d",
        "surface": "#f8f9fa",
        "on-surface": "#191c1d",
        "surface-variant": "#e1e3e4",
        "on-surface-variant": "#3b494c",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-bright": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-tint": "#006877",
        "outline": "#6b7a7d",
        "outline-variant": "#bac9cd",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        "inverse-primary": "#00daf8",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#001f25",
        "on-primary-fixed-variant": "#004e5a",
        "on-secondary-fixed": "#3a0033",
        "on-secondary-fixed-variant": "#840076",
        "on-tertiary-fixed": "#012200",
        "on-tertiary-fixed-variant": "#075300",
      },
      // ─── SPACING ───────────────────────────────────────────────────────
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "48px",
        "gutter": "24px",
        "unit": "4px",
        "margin-mobile": "20px",
        "container-max": "1280px",
      },
      // ─── BORDER RADIUS ─────────────────────────────────────────────────
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "1rem",
        "full": "9999px",
      },
      // ─── FONT FAMILIES ─────────────────────────────────────────────────
      fontFamily: {
        "display-lg": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        // Dark / mobile
        "display-lg-mobile": ["Anybody", "sans-serif"],
        "headline-md": ["Anybody", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
      },
      // ─── FONT SIZES ────────────────────────────────────────────────────
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "36px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        // Dark / mobile
        "label-mono": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg-mobile": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "900" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
